version: "3.9"

services:
  server:
    build:
      context: ./server
    image: myapp-server # Rename me
    container_name: myapp-server # Rename me
    command: yarn start:dev
    volumes:
      - ./server/:/app/server
      - /app/server/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      NODE_ENV: development
    networks:
      - app-network

  mongo:
    image: mongo
    # environment:  // If Mongo Authorization is need to be enabled
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./client
    image: myapp-client # Rename me
    container_name: myapp-client # Rename me
    command: yarn start
    volumes:
      - ./client/:/app/client
      - /app/client/node_modules
    depends_on:
      - server
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
